# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Kwiki-Export
version:      0.01
version_from: lib/Kwiki/Export.pm
installdirs:  site
requires:
    HTML::WikiConverter:           0.5
    Kwiki:                         0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
